### ISSUE TITLE
Backend causes error if no image tag present in config

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#179]
# Version
Alpha3

# What happened?

If an image tag is not present in the backend config, it will cause oc-mirror to exit with an error. 

# What you expected to happen?

oc-mirror should assign an image tag if none is specified

# How to reproduce it (as minimally and precisely as possible)?

attempt differential operations with a backend imageURL with an excluded image tag

# Anything else we need to know?

```
./bin/oc-mirror --config ~/release-imageset-config.yaml file://demo
INFO Verifying pull secrets                       
INFO Found: oc-mirror-workspace/src/publish       
INFO Found: oc-mirror-workspace/src/v2            
INFO Found: oc-mirror-workspace/src/charts        
2021/11/18 06:19:39 GET /v2/
2021/11/18 06:19:39 GET /v2/_catalog?n=1000
panic: runtime error: slice bounds out of range [:14] with length 13

goroutine 1 [running]:
github.com/RedHatGov/bundle/pkg/metadata/storage.(*registryBackend).repoExists(0xc00086fa40, {0x36eb270, 0xc000058068})
        /mnt/registry/alex/pkg/metadata/storage/registry.go:250 +0x2b7
github.com/RedHatGov/bundle/pkg/metadata/storage.(*registryBackend).exists(0xc00018c0e0, {0x36eb270, 0xc000058068})
        /mnt/registry/alex/pkg/metadata/storage/registry.go:191 +0x28
github.com/RedHatGov/bundle/pkg/metadata/storage.(*registryBackend).ReadMetadata(0xc00086fa40, {0x36eb270, 0xc000058068}, 0x17, {0xc000147098, 0x16})
        /mnt/registry/alex/pkg/metadata/storage/registry.go:61 +0xc5
github.com/RedHatGov/bundle/pkg/cli/mirror.MirrorOptions.Create({0xc00085c480, {0x7ffd50de72d2, 0x4}, {0x7ffd50de729f, 0x2b}, 0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...}, ...)
        /mnt/registry/alex/pkg/cli/mirror/create.go:51 +0x2ba
github.com/RedHatGov/bundle/pkg/cli/mirror.(*MirrorOptions).Run(0xc00001c900, 0x0, {0x3744f00, 0xc000860ac0})
        /mnt/registry/alex/pkg/cli/mirror/mirror.go:124 +0x4f5
github.com/RedHatGov/bundle/pkg/cli/mirror.NewMirrorCmd.func1(0xc0000ec780, {0xc000838820, 0x5, 0x5})
        /mnt/registry/alex/pkg/cli/mirror/mirror.go:62 +0x85
github.com/spf13/cobra.(*Command).execute(0xc0000ec780, {0xc00004e1f0, 0x5, 0x5})
        /home/ec2-user/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000ec780)
        /home/ec2-user/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ec2-user/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /mnt/registry/alex/cmd/oc-mirror/main.go:27 +0x172
```

**Comment by jpower432** [comment]
Related to #154
